/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AdsService } from "../ads.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AdsCreateInput } from "./AdsCreateInput";
import { Ads } from "./Ads";
import { AdsFindManyArgs } from "./AdsFindManyArgs";
import { AdsWhereUniqueInput } from "./AdsWhereUniqueInput";
import { AdsUpdateInput } from "./AdsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AdsControllerBase {
  constructor(
    protected readonly service: AdsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ads })
  @nestAccessControl.UseRoles({
    resource: "Ads",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AdsCreateInput,
  })
  async createAds(@common.Body() data: AdsCreateInput): Promise<Ads> {
    return await this.service.createAds({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        platform: true,
        adId: true,
        clicks: true,
        impressions: true,
        revenue: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Ads] })
  @ApiNestedQuery(AdsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Ads",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async adsItems(@common.Req() request: Request): Promise<Ads[]> {
    const args = plainToClass(AdsFindManyArgs, request.query);
    return this.service.adsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        platform: true,
        adId: true,
        clicks: true,
        impressions: true,
        revenue: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ads })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ads",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ads(@common.Param() params: AdsWhereUniqueInput): Promise<Ads | null> {
    const result = await this.service.ads({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        platform: true,
        adId: true,
        clicks: true,
        impressions: true,
        revenue: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ads })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ads",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AdsUpdateInput,
  })
  async updateAds(
    @common.Param() params: AdsWhereUniqueInput,
    @common.Body() data: AdsUpdateInput
  ): Promise<Ads | null> {
    try {
      return await this.service.updateAds({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          platform: true,
          adId: true,
          clicks: true,
          impressions: true,
          revenue: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ads })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ads",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAds(
    @common.Param() params: AdsWhereUniqueInput
  ): Promise<Ads | null> {
    try {
      return await this.service.deleteAds({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          platform: true,
          adId: true,
          clicks: true,
          impressions: true,
          revenue: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
